### ISSUE TITLE
Error: scRepertoire >= 2.0.8 is required

### ISSUE THREAD

**Issue by pwwang** [pwwang/scplotter#2]
scRepertoire 2.0.8 is not yet released. You need to:

```r
devtools::install_github("ncborcherding/scRepertoire")  # or
remotes::install_github("ncborcherding/scRepertoire")
```

**Comment by ncborcherding** [comment]
Just got everything pushed to bioconductor with the changes you helped with as version 2.2.1.

Starting tomorrow, users can install with: 
```
BiocManager::install("scRepertoire")
```
