### ISSUE TITLE
Error using split.by in ClonalOverlapPlot when the data is unpaired. 

### ISSUE THREAD

**Issue by xyfqwlzoe** [pwwang/scplotter#3]
Hi,
Thank you for developing this package. It’s user-friendly, and the figures look fantastic!
I encountered errors using split.by in ClonalOverlapPlot when the data is unpaired. For example, sample A has five categories for group I, while sample B only has values for three of those categories.
`> ClonalOverlapPlot(combined, group_by = "donor", split_by = "group_I")
Error in if (any(inds)) { : missing value where TRUE/FALSE needed`

**Comment by pwwang** [comment]
Do you mind sharing the `combined`, or a piece of it?

**Comment by xyfqwlzoe** [comment]
> Do you mind sharing the `combined`, or a piece of it?

Sure, no problem. Just sent it to you.

**Comment by pwwang** [comment]
Fixed by https://github.com/pwwang/plotthis/commit/1885016ea43b1f5470b5a844121ec0e84a62fc24
