### ISSUE TITLE
DimPlot vs CellDimPlot 

### ISSUE THREAD

**Issue by kerardu** [pwwang/scplotter#7]
Hi,

I was trying the CellDimPlot and not getting similar umap plot (when compared to the DimPlot). I was using the same dataset. Do I need to use additional arguments for this? For DimPlot, the clusters were well-defined and labeled, while the CellDimPlot, the clusters seemed to be integrated all over. 

DimPlot(seurat_obj,
       reduction = 'umap',
       group.by = 'cellType', 
       label = T)

CellDimPlot(seurat_obj,
            reduction = 'umap',
            group_by = 'cellType',  
            label = TRUE, 
            label_insitu = TRUE
)

**Comment by pwwang** [comment]
Can you post the two plots here?

**Comment by kerardu** [comment]
<img width="414" alt="Screenshot 2024-11-02 at 11 42 10 AM" src="https://github.com/user-attachments/assets/86c364db-66fd-47e9-be5d-ee3182b9dfb0">
<img width="421" alt="Screenshot 2024-11-02 at 11 42 01 AM" src="https://github.com/user-attachments/assets/d65d169f-d2cf-4ead-89f7-ace485dbccce">

**Comment by pwwang** [comment]
Could you downsample the cells (e.g. to 1000 cells) and see if they are still inconsistent? If so, could you share the downsampled seurat object?

**Comment by kerardu** [comment]
I tried 250,000 cells and it's working.

**Comment by pwwang** [comment]
Do you mind sharing the entire object? Curious about the inconsistency.

**Comment by kerardu** [comment]
Thank you for your interest! However, I'm unable to share the entire object due to data privacy agreements in place.

**Comment by pwwang** [comment]
Then could you try shuffling the cells (downsampling to the total number of cells)?

**Comment by pwwang** [comment]
Closing. Feel free to reopen if needed.
